apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "app.secretProviderClassName" . }}
  labels: {{ include "app.labels" . | nindent 4 }}

spec:
  secretObjects:
  - secretName: {{ template "app.dbsecrets.secretName" . }}
    type: Opaque
    labels:                                   
      provider: "csi-driver"
    data:
    - objectName: csi-db-username
      key: username
    - objectName: csi-db-password
      key: password
    - objectName: csi-db-host
      key: host
  - secretName: {{ template "app.jwtsecrets.external.secretName" . }}
    type: Opaque
    labels:
      provider: "csi-driver"
    data:
    - objectName: csi-security-external-private-key
      key: jwt_signature_privatekey
  - secretName: {{ template "app.jwtsecrets.internal.secretName" . }}
    type: Opaque
    labels:
      provider: "csi-driver"
    data:
    - objectName: csi-security-internal-private-key
      key: internal_jwt_signature_privatekey

  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.global.secrets.database.secretKey | quote }}
        objectType: "secretsmanager"
        objectAlias: {{ template "app.dbsecrets.secretName" . }}
        jmesPath:
        - path: "username"
          objectAlias: "csi-db-username"
        - path: "password"
          objectAlias: "csi-db-password"
        - path: "host"
          objectAlias: "csi-db-host"
      - objectName: {{ .Values.global.secrets.jwtExternalPrivateKey.awsSecretKeyName | quote }}
        objectType: "secretsmanager"
        objectAlias: {{ template "app.jwtsecrets.external.secretName" . }}
        jmesPath:
        - path: "jwt_signature_privatekey"
          objectAlias: "csi-security-external-private-key"
      - objectName: {{ .Values.global.secrets.jwtInternalPrivateKey.awsSecretKeyName | quote }}
        objectType: "secretsmanager"
        objectAlias: {{ template "app.jwtsecrets.internal.secretName" . }}
        jmesPath:
        - path: "internal_jwt_signature_privatekey"
          objectAlias: "csi-security-internal-private-key"