# Default values for d360-analysis-config-storage-api-service
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  name: d360-analysis-config-storage-api-service
  tag: "1.0.1"

service:
  http:
    port: 8080

jvm:
  javaOpts: -Xms1g -Xmx1g

resources:
  limits:
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi