apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-configmap
  labels: {{ include "app.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  app_mysql_port: {{ .Values.global.db.mysql.port | quote }}
  app_jvm_javaOpts: {{ .Values.jvm.javaOpts }}
  app_grpc_metrics_service_host: {{ .Values.global.grpcclients.metricsservice.host | quote }}
  app_grpc_metrics_service_port: {{ .Values.global.grpcclients.metricsservice.port | quote }}
  app_open_search_host: {{ .Values.global.db.opensearch.host | quote }}