apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "app.secretProviderClassName" . }}
  labels: {{ include "app.labels" . | nindent 4 }}

spec:
  secretObjects:
  - secretName: {{ template "app.dbsecrets.secretName" . }}
    type: Opaque
    labels:                                   
      provider: "csi-driver"
    data:
    - objectName: csi-db-username
      key: username
    - objectName: csi-db-password
      key: password
    - objectName: csi-db-host
      key: host
  - secretName: {{ template "app.wtsecrets.secretName" . }}
    type: Opaque
    labels:                                   
      provider: "csi-driver"
    data:
    - objectName: csi-jwt-public-key
      key: public_key
      
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.global.secrets.database.secretKey | quote }}
        objectType: "secretsmanager"
        objectAlias: {{ template "app.dbsecrets.secretName" . }}
        jmesPath:
        - path: "username"
          objectAlias: "csi-db-username"
        - path: "password"
          objectAlias: "csi-db-password"
        - path: "host"
          objectAlias: "csi-db-host"
      - objectName: {{ .Values.global.secrets.jwt.secretKey | quote }}
        objectType: "secretsmanager"
        objectAlias: {{ template "app.wtsecrets.secretName" . }}
        jmesPath:
        - path: "public_key"
          objectAlias: "csi-jwt-public-key"